### ISSUE TITLE
Great program! I did find a small typo

### ISSUE THREAD

**Issue by rathurma** [covermymeds/phpIPAM-api#2]
In getFreeIP.php, line 92, I kept getting errors when trying to execute it in my environment.  I changed "executeQuery" to "query" and it works like a champ.  I intend to use this heavily in my lab, great job :-)

$id = $data->query($query,true);

**Comment by dugdigg** [comment]
Thanks for the heads up, I'll take a look.  BTW what operating system are you running this on?

**Comment by rathurma** [comment]
I'm running Ubuntu 14.04

**Comment by dugdigg** [comment]
ok, well I'll merge this probably Monday.

**Comment by dugdigg** [comment]
Interesting because the syntax works fine on RHEL/CentOS, but so does what you suggested.
